### **🔎** 핵심정리

- 애너테이션으로 할 수 있는 일을 명명패턴으로 처리할 이유는 없다
- 자바 프로그래머라면 예외 없이 자바가 제공하는 애너테이션 타입들은 사용해야한다.

- 전통적으로 도구나 프레임워크가 특별히 다뤄야할 프로그램 요소에는 딱 구분되는 명명 패턴을 적용해왔다.

### ✔️ 명명패턴의 단점

1. 오타가 나면 안된다.
2. 올바른 프로그램 요소에서만 사용되리라 보증할 방법이 없다.
3. 프로그램 요소를 매개변수로 전달할 마땅한 방법이 없다.

### ✔️ 애터네이션(해결책!)

**meta-annotation.**

코드39-1.  마커 애너테이션타입 선언

```java
package Enum;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/*
테스트 메서드임을 선언하는 애너테이션이다.
매개변수 없는 정적 메서드 전용이다.
*/
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface Test {
    
}
```

### ✔️ 메타애너테이션 : 애너테이션 선언에 다는 애너테이션(@Test 애너테이션을 쓸 수 있게 해줌)

위 코드에서는 @Target, @Retention 이 메타애너테이션이다.

@Retention 

- @Test가 런타임에도 유지되어야 한다는 표시
- 만약 이 메타애너테이션을 생략하면 테스트 도구는 @Test를 인식할 수 없다.

@Target 

- @Test가 반드시 메서드 선언에서만 사용돼야 한다고 알려준다.
- 따라서 클래스 선언, 필드 선언 등 다른 프로그램 요소에는 달 수 없다.

### ✔️ @Test 애너테이션을 실제 적용

코드 39-2

```java
public class Sample {
    @Test public static void m1() { } //성공
    public static void m2() { } // 테스트 도구가 무시
    @Test public static void m3() { //실패
        throw new RuntimeException("실패");
    }

    public static void m4() { } //테스트 도구가 무시
    @Test public void m5() { } // 잘못 사용한 예(정적메서드가 아니다)
    public static void m6() { } // 테스트 도구가 무시
    @Test public static void m7() { //실패
        throw new RuntimeException("실패");
    }
    
    public static void m8() { } //테스트 도구가 무시
}
```

- 정적 메서드 7개 中 4개에 @Test를 달았다. (static 붙어 있는 메소드들)
- 예외처리 : m3, m7(예외처리 안함 : m1, m5)
- m5는 인스턴스 메서드(@Test를 잘못 사용한 경우)
- @Test를 붙이지 않은 나머지 4개의 메서드는 테스트 도구가 무시할 것이다.
- @Test 애너테이션이 Sample 클래스의 의미에 직접적인 영향을 주지는 않는다. @Test 애너테이션에 관심 있는 프로그램에게 추가 정보를 제공할 뿐이다.

코드 39-3 마커 애너테이션을 처리하는 프로그램

```java
package Enum;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

// 마커 애너테이션 처리기
public class RunTests {
    public static void main(String[] args) throws Exception {
				//전체 테스트 횟수 및 성공한 테스트 횟수를 추적하는 변수
        int tests = 0;
        int passed = 0;
				//명령줄에서 전달된 클래스 이름을 사용하여 Class 객체를 얻음
        Class<?> testClass = Class.forName(args[0]);
				// 클래스의 모든 메서드를 확인하며 마커 애너테이션이 지정된 메서드를 찾아 실행
        for (Method m : testClass.getDeclaredMethods()) {
            if (m.isAnnotationPresent(Test.class)) {
                tests++;
                try {
                    m.invoke(null);
                    passed++;
                } catch (InvocationTargetException wrappedExc) {
										//예외가 발생한 경우 해당 예외를 출
                    Throwable exc = wrappedExc.getCause();
                    System.out.println(m + " 실패: " + exc);
                } catch (Exception exc) {
										// 예상치 못한 예외가 발생한 경우 메시지 출력
                    System.out.println("잘못 사용한 @Test: " + m);
                }
            }
        }
        System.out.printf("성공: %d, 실패: %d%n",
                passed, tests - passed);
    }
}
```

- 이 테스트 러너는 명령줄로부터 완전 정규화된 클래스 이름을 받아, 그 클래스에서 @Test 애너테이션이 달린 메서드를 차례로 호출한다.
- isAnnotationPresent가 실행할 메서드를 찾아주는 메서드다. 테스트 메서드가 예외를 던지면 리플렉션 메커니즘이 IncovationTargetException으로 감싸서 다시 던진다.
- 그래서 이 프로그램은 InvocationTargerException을 잡아 원래 예외에 담긴 실패 정보를 추출해(getCause) 출력한다.
- 오류뜸…

```java
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at Enum.RunTests.main(RunTests.java:11)

Process finished with exit code 1

============================================
여기서 "Index 0 out of bounds for length 0"라는 부분은 배열의 길이가 0인데 0번째 인덱스를 참조하려고 했기 때문에 발생한 예외입니다.

가장 가능성 있는 원인은 args 배열의 길이가 0이라서 args[0]에서 ArrayIndexOutOfBoundsException가 발생한 것입니다. 즉, 명령줄에서 클래스 이름을 전달하지 않았거나 잘못된 방식으로 프로그램을 실행했을 가능성이 있습니다.

프로그램을 실행할 때 클래스 이름을 명령줄 매개변수로 전달하는지 확인하십시오.
```

### ✔️배열 배개변수를 받는 애터네이션용 문법

코드 39-9. 반복 가능 애터네이션을 두 번 단 코드

```java
@ExceptionTest(IndexOutOfBoundsException.class)
@ExceptionTest(NullPointerException.class)
public static void doublyBad() {...}
```

- 반복 가능 애너테이션을 여러 개 달면 하나만 달았을 때와 구분하기 위해 해당 ‘컨테이너’ 애너테이션 타입이 적용된다.

### 📌 Reference
- https://jjingho.tistory.com/86